import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; 
import NavbarCom from "./components/NavbarCom";
import ReduxProvider from "./components/ReduxProvider";
import ThemeEffect, { ThemeFAB } from "./components/ThemeEffect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} flex`}>
        <ReduxProvider>
          <ThemeEffect />
          <NavbarCom />
          <ThemeFAB />
          <main className="flex-1 lg:ml-[16.666667%] lg:pt-0 pt-8 pb-14 lg:pb-0 min-h-screen">
            {children}
          </main>
        </ReduxProvider>
      </body>
    </html>
  );
}
